### ISSUE TITLE
Issue with dragging cells to reorder

### ISSUE THREAD

**Issue by ianrblue** [Dromaguirre/DRCellSlideGestureRecognizer#13]
When the table view is populated with enough cells that it becomes scrollable, an odd behavior occurs when dragging to reorder these cells.  If the table view is scrolled all the way to the top, everything works as expected.  Depending on how far down you scroll the tableview, the drag to reorder cells animation will be offset by this same distance.  I noticed this issue in both the sample project and when I added PDGestureTableView to my own project.

**Comment by Dromaguirre** [comment]
Please take a look at #15, where I explain how the future of this library will be.

**Comment by Dromaguirre** [comment]
As you can see, I just released DRCellSlideGestureTableView, which will replace PDGestureTableView from now on as I explain in #15. I have a couple more projects in mind before I release DRCellMoveGestureTableView, so I'll close this for now until such release.
